# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_linkDialog(object):
    def setupUi(self, linkDialog):
        linkDialog.setObjectName("linkDialog")
        linkDialog.resize(436, 205)
        self.button_box = QtWidgets.QDialogButtonBox(parent=linkDialog)
        self.button_box.setGeometry(QtCore.QRect(20, 170, 341, 32))
        self.button_box.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.button_box.setObjectName("button_box")
        self.link_box = QtWidgets.QLineEdit(parent=linkDialog)
        self.link_box.setGeometry(QtCore.QRect(20, 60, 401, 26))
        self.link_box.setObjectName("link_box")
        self.label = QtWidgets.QLabel(parent=linkDialog)
        self.label.setGeometry(QtCore.QRect(20, 10, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.quality_selector = QtWidgets.QComboBox(parent=linkDialog)
        self.quality_selector.setGeometry(QtCore.QRect(80, 100, 79, 26))
        self.quality_selector.setObjectName("quality_selector")
        self.quality_selector.addItem("")
        self.quality_selector.addItem("")
        self.quality_selector.addItem("")
        self.quality_selector.addItem("")
        self.quality_selector.addItem("")
        self.quality_selector.addItem("")
        self.label_2 = QtWidgets.QLabel(parent=linkDialog)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 58, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.remove_music_box = QtWidgets.QCheckBox(parent=linkDialog)
        self.remove_music_box.setGeometry(QtCore.QRect(20, 140, 121, 23))
        self.remove_music_box.setChecked(True)
        self.remove_music_box.setObjectName("remove_music_box")

        self.retranslateUi(linkDialog)
        self.button_box.accepted.connect(linkDialog.accept) # type: ignore
        self.button_box.rejected.connect(linkDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(linkDialog)

    def retranslateUi(self, linkDialog):
        _translate = QtCore.QCoreApplication.translate
        linkDialog.setWindowTitle(_translate("linkDialog", "Dialog"))
        self.label.setText(_translate("linkDialog", "Insert the link"))
        self.quality_selector.setItemText(0, _translate("linkDialog", "144p"))
        self.quality_selector.setItemText(1, _translate("linkDialog", "240p"))
        self.quality_selector.setItemText(2, _translate("linkDialog", "360p"))
        self.quality_selector.setItemText(3, _translate("linkDialog", "480p"))
        self.quality_selector.setItemText(4, _translate("linkDialog", "720p"))
        self.quality_selector.setItemText(5, _translate("linkDialog", "1080p"))
        self.label_2.setText(_translate("linkDialog", "Quality"))
        self.remove_music_box.setText(_translate("linkDialog", "Remove Music"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    linkDialog = QtWidgets.QDialog()
    ui = Ui_linkDialog()
    ui.setupUi(linkDialog)
    linkDialog.show()
    sys.exit(app.exec())
