# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.10.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(999, 471)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(270, 0, 221, 61))
        self.label.setTextFormat(QtCore.Qt.TextFormat.MarkdownText)
        self.label.setObjectName("label")
        self.start_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.start_button.setGeometry(QtCore.QRect(20, 260, 461, 71))
        self.start_button.setObjectName("start_button")
        self.source_chooser = QtWidgets.QComboBox(parent=self.centralwidget)
        self.source_chooser.setGeometry(QtCore.QRect(20, 100, 461, 51))
        self.source_chooser.setObjectName("source_chooser")
        self.source_chooser.addItem("")
        self.source_chooser.addItem("")
        self.source_chooser.addItem("")
        self.language_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.language_button.setGeometry(QtCore.QRect(390, 390, 86, 26))
        self.language_button.setObjectName("language_button")
        self.progress_bar = QtWidgets.QProgressBar(parent=self.centralwidget)
        self.progress_bar.setGeometry(QtCore.QRect(20, 350, 461, 23))
        self.progress_bar.setProperty("value", 0)
        self.progress_bar.setObjectName("progress_bar")
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(500, 10, 481, 411))
        self.textBrowser.setObjectName("textBrowser")
        self.language_button_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.language_button_2.setGeometry(QtCore.QRect(20, 390, 86, 26))
        self.language_button_2.setObjectName("language_button_2")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 170, 241, 18))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.output_directory_label = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.output_directory_label.setEnabled(True)
        self.output_directory_label.setGeometry(QtCore.QRect(20, 190, 461, 26))
        self.output_directory_label.setReadOnly(True)
        self.output_directory_label.setObjectName("output_directory_label")
        self.output_directory_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.output_directory_button.setGeometry(QtCore.QRect(20, 220, 86, 26))
        self.output_directory_button.setObjectName("output_directory_button")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 70, 241, 18))
        font = QtGui.QFont()
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 999, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "# Music Remover"))
        self.start_button.setText(_translate("MainWindow", "Start "))
        self.source_chooser.setItemText(0, _translate("MainWindow", "From Link"))
        self.source_chooser.setItemText(1, _translate("MainWindow", "From Playlist"))
        self.source_chooser.setItemText(2, _translate("MainWindow", "From File"))
        self.language_button.setText(_translate("MainWindow", "تغيير للعربية"))
        self.language_button_2.setText(_translate("MainWindow", "Help"))
        self.label_2.setText(_translate("MainWindow", "Output Directory:"))
        self.output_directory_button.setText(_translate("MainWindow", "Change"))
        self.label_3.setText(_translate("MainWindow", "Source:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
