# Form implementation generated from reading ui file '/home/Yehia/repos/music-remover/GUI/settings.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SettingsDialog(object):
    def setupUi(self, SettingsDialog):
        SettingsDialog.setObjectName("SettingsDialog")
        SettingsDialog.resize(400, 530)
        self.gpu_checkbox = QtWidgets.QCheckBox(parent=SettingsDialog)
        self.gpu_checkbox.setGeometry(QtCore.QRect(20, 20, 360, 24))
        self.gpu_checkbox.setChecked(True)
        self.gpu_checkbox.setObjectName("gpu_checkbox")
        self.gpu_status = QtWidgets.QLabel(parent=SettingsDialog)
        self.gpu_status.setGeometry(QtCore.QRect(20, 44, 360, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setItalic(True)
        self.gpu_status.setFont(font)
        self.gpu_status.setText("")
        self.gpu_status.setObjectName("gpu_status")
        self.tensorrt_checkbox = QtWidgets.QCheckBox(parent=SettingsDialog)
        self.tensorrt_checkbox.setGeometry(QtCore.QRect(40, 62, 340, 24))
        self.tensorrt_checkbox.setChecked(False)
        self.tensorrt_checkbox.setObjectName("tensorrt_checkbox")
        self.gpu_threads_label = QtWidgets.QLabel(parent=SettingsDialog)
        self.gpu_threads_label.setGeometry(QtCore.QRect(40, 90, 101, 24))
        self.gpu_threads_label.setObjectName("gpu_threads_label")
        self.gpu_threads_spinbox = QtWidgets.QSpinBox(parent=SettingsDialog)
        self.gpu_threads_spinbox.setGeometry(QtCore.QRect(150, 90, 100, 26))
        self.gpu_threads_spinbox.setMinimum(1)
        self.gpu_threads_spinbox.setMaximum(2)
        self.gpu_threads_spinbox.setProperty("value", 1)
        self.gpu_threads_spinbox.setObjectName("gpu_threads_spinbox")
        self.chunking_checkbox = QtWidgets.QCheckBox(parent=SettingsDialog)
        self.chunking_checkbox.setGeometry(QtCore.QRect(20, 125, 360, 24))
        self.chunking_checkbox.setChecked(True)
        self.chunking_checkbox.setObjectName("chunking_checkbox")
        self.label = QtWidgets.QLabel(parent=SettingsDialog)
        self.label.setGeometry(QtCore.QRect(20, 160, 121, 24))
        self.label.setObjectName("label")
        self.chunk_duration_combo = QtWidgets.QComboBox(parent=SettingsDialog)
        self.chunk_duration_combo.setGeometry(QtCore.QRect(150, 160, 100, 26))
        self.chunk_duration_combo.setObjectName("chunk_duration_combo")
        self.chunk_duration_combo.addItem("")
        self.chunk_duration_combo.addItem("")
        self.chunk_duration_combo.addItem("")
        self.cpu_threads_label = QtWidgets.QLabel(parent=SettingsDialog)
        self.cpu_threads_label.setGeometry(QtCore.QRect(20, 195, 121, 24))
        self.cpu_threads_label.setObjectName("cpu_threads_label")
        self.cpu_threads_spinbox = QtWidgets.QSpinBox(parent=SettingsDialog)
        self.cpu_threads_spinbox.setGeometry(QtCore.QRect(150, 195, 100, 26))
        self.cpu_threads_spinbox.setMinimum(1)
        self.cpu_threads_spinbox.setMaximum(4)
        self.cpu_threads_spinbox.setProperty("value", 2)
        self.cpu_threads_spinbox.setObjectName("cpu_threads_spinbox")
        self.retry_chunks_checkbox = QtWidgets.QCheckBox(parent=SettingsDialog)
        self.retry_chunks_checkbox.setGeometry(QtCore.QRect(20, 230, 360, 24))
        self.retry_chunks_checkbox.setChecked(True)
        self.retry_chunks_checkbox.setObjectName("retry_chunks_checkbox")
        self.line = QtWidgets.QFrame(parent=SettingsDialog)
        self.line.setGeometry(QtCore.QRect(20, 265, 360, 20))
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setObjectName("line")
        self.label_2 = QtWidgets.QLabel(parent=SettingsDialog)
        self.label_2.setGeometry(QtCore.QRect(20, 285, 121, 24))
        self.label_2.setObjectName("label_2")
        self.default_quality_combo = QtWidgets.QComboBox(parent=SettingsDialog)
        self.default_quality_combo.setGeometry(QtCore.QRect(150, 285, 100, 26))
        self.default_quality_combo.setObjectName("default_quality_combo")
        self.default_quality_combo.addItem("")
        self.default_quality_combo.addItem("")
        self.default_quality_combo.addItem("")
        self.default_quality_combo.addItem("")
        self.default_quality_combo.addItem("")
        self.default_quality_combo.addItem("")
        self.label_3 = QtWidgets.QLabel(parent=SettingsDialog)
        self.label_3.setGeometry(QtCore.QRect(20, 325, 121, 24))
        self.label_3.setObjectName("label_3")
        self.default_output_path = QtWidgets.QLineEdit(parent=SettingsDialog)
        self.default_output_path.setGeometry(QtCore.QRect(20, 350, 280, 26))
        self.default_output_path.setObjectName("default_output_path")
        self.browse_output_button = QtWidgets.QPushButton(parent=SettingsDialog)
        self.browse_output_button.setGeometry(QtCore.QRect(310, 350, 70, 26))
        self.browse_output_button.setObjectName("browse_output_button")
        self.remove_music_checkbox = QtWidgets.QCheckBox(parent=SettingsDialog)
        self.remove_music_checkbox.setGeometry(QtCore.QRect(20, 390, 360, 24))
        self.remove_music_checkbox.setChecked(True)
        self.remove_music_checkbox.setObjectName("remove_music_checkbox")
        self.benchmarking_checkbox = QtWidgets.QCheckBox(parent=SettingsDialog)
        self.benchmarking_checkbox.setGeometry(QtCore.QRect(20, 420, 360, 24))
        self.benchmarking_checkbox.setObjectName("benchmarking_checkbox")
        self.clear_cache_button = QtWidgets.QPushButton(parent=SettingsDialog)
        self.clear_cache_button.setGeometry(QtCore.QRect(20, 455, 360, 26))
        self.clear_cache_button.setObjectName("clear_cache_button")
        self.line_2 = QtWidgets.QFrame(parent=SettingsDialog)
        self.line_2.setGeometry(QtCore.QRect(20, 490, 360, 20))
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setObjectName("line_2")
        self.button_box = QtWidgets.QDialogButtonBox(parent=SettingsDialog)
        self.button_box.setGeometry(QtCore.QRect(20, 510, 360, 32))
        self.button_box.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.button_box.setStandardButtons(
            QtWidgets.QDialogButtonBox.StandardButton.Cancel
            | QtWidgets.QDialogButtonBox.StandardButton.Save
        )
        self.button_box.setObjectName("button_box")

        self.retranslateUi(SettingsDialog)
        self.chunk_duration_combo.setCurrentIndex(1)
        self.button_box.accepted.connect(SettingsDialog.accept)  # type: ignore
        self.button_box.rejected.connect(SettingsDialog.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(SettingsDialog)

    def retranslateUi(self, SettingsDialog):
        _translate = QtCore.QCoreApplication.translate
        SettingsDialog.setWindowTitle(_translate("SettingsDialog", "Settings"))
        self.gpu_checkbox.setText(_translate("SettingsDialog", "GPU Acceleration"))
        self.tensorrt_checkbox.setText(
            _translate("SettingsDialog", "Use TensorRT (6GB+ VRAM)")
        )
        self.gpu_threads_label.setText(_translate("SettingsDialog", "GPU Threads:"))
        self.chunking_checkbox.setText(
            _translate("SettingsDialog", "Chunking (files larger than 50MB)")
        )
        self.label.setText(_translate("SettingsDialog", "Chunk Duration:"))
        self.chunk_duration_combo.setItemText(0, _translate("SettingsDialog", "30s"))
        self.chunk_duration_combo.setItemText(1, _translate("SettingsDialog", "60s"))
        self.chunk_duration_combo.setItemText(2, _translate("SettingsDialog", "120s"))
        self.cpu_threads_label.setText(_translate("SettingsDialog", "CPU Threads:"))
        self.retry_chunks_checkbox.setText(
            _translate("SettingsDialog", "Retry failed chunks")
        )
        self.label_2.setText(_translate("SettingsDialog", "Default Quality:"))
        self.default_quality_combo.setItemText(0, _translate("SettingsDialog", "144p"))
        self.default_quality_combo.setItemText(1, _translate("SettingsDialog", "240p"))
        self.default_quality_combo.setItemText(2, _translate("SettingsDialog", "360p"))
        self.default_quality_combo.setItemText(3, _translate("SettingsDialog", "480p"))
        self.default_quality_combo.setItemText(4, _translate("SettingsDialog", "720p"))
        self.default_quality_combo.setItemText(5, _translate("SettingsDialog", "1080p"))
        self.label_3.setText(_translate("SettingsDialog", "Default Output Path:"))
        self.default_output_path.setPlaceholderText(
            _translate("SettingsDialog", "Leave empty for current directory")
        )
        self.browse_output_button.setText(_translate("SettingsDialog", "Browse"))
        self.remove_music_checkbox.setText(
            _translate("SettingsDialog", "Remove music by default (YouTube downloads)")
        )
        self.benchmarking_checkbox.setText(
            _translate("SettingsDialog", "Benchmarking (log performance data to CSV)")
        )
        self.clear_cache_button.setText(
            _translate("SettingsDialog", "Clear Download Cache")
        )


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    SettingsDialog = QtWidgets.QDialog()
    ui = Ui_SettingsDialog()
    ui.setupUi(SettingsDialog)
    SettingsDialog.show()
    sys.exit(app.exec())
